[tool.poetry]
name = "unopt"
version = "0.1.0"
description = ""
authors = ["vprusso <vincentrusso1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
qiskit = "^1.2.4"
numpy = ">=1.22,<2.0"
mitiq = "^0.40.0"
jupyter = "^1.1.1"
matplotlib = "^3.9.2"
pylatexenc = "^2.10"
ply = "^3.11"
qiskit-aer = "^0.15.1"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
